import Image from 'next/image'
import { Inter } from 'next/font/google'
import {useState, useEffect} from 'react'
import { ethers } from 'ethers'
import axios from 'axios'
import { VotingAddress } from '../../contracts'
import Voting from '../contracts/Voting.json'
import Head from 'next/head'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [account, setAccount] = useState('')
  const [chainId, setChainId] = useState(false)
  const [numOfVoters, setNumOfVoters] = useState('')
  const [winner, setWinner] = useState('')
  const [owner, setOwner] = useState('')
  const [result, setResult] = useState({ names: '', medians: '', ranks: ''});
  const [individualResult, setIndividualResult] = useState({ MedianValue: '', Rank: '', ScoreGet: ''});
  const [getVoterScores, setGetVoterScores] = useState([])
  const [ForOwnerGet,setForOwnerGet] = useState([])
  const [VoteEnded, setVoteEnded] = useState(false)
  const mumbaiId = "0x13881";
  const zeroAddress = "0x0000000000000000000000000000000000000000";

  const checkMetaMaskInstalled = async () => {
    const { ethereum } = window;
    if (!ethereum) {
      alert('MetaMaskをインストールしてください！');
    }
  }
  useEffect(() => {
    checkMetaMaskInstalled()
  }, [])
  return (
    <div className={'flex flex-col items-center bg-slate-100 text-blue-900 min-h-screen'}>
      <Head>
        <title>VotingDApp</title>
        <meta name ="description" content="Generated by create next app"></meta>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <h2 className={"text-6xl font-bold my-12 mt-8"}>
        投票アプリへようこそ
      </h2>
      <div className='mt-8 mb-16 hover:rotate-180 hover:scale-105 transition duration-700 ease-in-out'>
        <svg
          xmlns='http://www.w3.org/2000/svg'
          width='160'
          height='160'
          viewBox='0 0 350 350'
        >
          <polygon points="0 0, 175 0, 175 175, 0 175" stroke="black" fill="#0000ff" />
          <polygon points="0 175, 175 175, 175 350, 0 350" stroke="black" fill="#ffc0cb" />
          <polygon points="175 0, 350 0, 350 175, 175 175" stroke="black" fill="#90EE90" />
          <polygon points="175 175, 350 175, 350 350, 175 350" stroke="black" fill="#ffff00" />
        </svg>
      </div>
    </div>
  )
}
